
all:
  vars:
    ansible_connection: ssh
    ansible_user: debian
    ansible_ssh_pass: root
    ansible_become: yes
    ansible_become_method: su
    ansible_become_user: root
    ansible_become_password: root

masters:
  hosts:
    k8s-mn-01:
      ip: 192.168.1.73
  vars:
    ansible_python_interpreter: /usr/bin/python3
workers:
  hosts:
    k8s-wn-01:
      ip: 192.168.1.74
  vars:
    ansible_python_interpreter: /usr/bin/python3
