---
- hosts: kubernetes-master-node
  become: yes
  vars_files:
  - env_variables
  tasks:

  - name: Initializing Kubernetes cluster
    shell: kubeadm init --pod-network-cidr 10.244.0.0/16 --control-plane-endpoint {{ad_addr}}:6443 --upload-certs
    register: output

  - name: Storing Logs and Generated token for future purpose.
    local_action: copy content={{ output.stdout }} dest={{ token_file }}
    become: False

  - name: create .kube directory
    become: yes
    file:
      path: $HOME/.kube
      state: directory
      mode: 0755

  - name: copy admin.conf to user's kube config
    copy:
      src: /etc/kubernetes/admin.conf
      dest: $HOME/.kube/config
      remote_src: yes

  - name: get kubeconfig
    fetch:
      src: /etc/kubernetes/admin.conf
      dest: /home/piranha900/.kube/config
      flat: yes

  - name: install Pod network
    become: yes
    shell: kubectl apply -f https://github.com/coreos/flannel/raw/master/Documentation/kube-flannel.yml

