---
- hosts: all
  become: yes
  vars_files:
  - env_variables
  tasks:
  - name: Creating a repository file for Kubernetes
    file:
     path: /etc/yum.repos.d/kubernetes.repo
     state: touch

  - name: Adding repository details in Kubernetes repo file.
    blockinfile:
     path: /etc/yum.repos.d/kubernetes.repo
     block: |
       [kubernetes]
       name=Kubernetes
       baseurl=https://packages.cloud.google.com/yum/repos/kubernetes-el7-\$basearch
       enabled=1
       gpgcheck=1
       repo_gpgcheck=1
       gpgkey=https://packages.cloud.google.com/yum/doc/yum-key.gpg https://packages.cloud.google.com/yum/doc/rpm-package-key.gpg
       exclude=kubelet kubeadm kubectl

  - name: Installing Docker #and firewalld
    shell: |
     yum install -y yum-utils device-mapper-persistent-data lvm2
     yum-config-manager --add-repo https://download.docker.com/linux/centos/docker-ce.repo
     yum install docker-ce docker-ce-cli containerd.io -y 

  - name: Resetting kubeadm
    shell: kubeadm reset -f
    register: output

  - name: Docker prune 
    shell: docker system prune -af

  - name: Deleting Interfaces 
    shell: |
     ip l delete cni0
     ip l delete flannel.1
    ignore_errors: yes

  - name: Resetting config
    shell: |
      rm -rf $HOME/.kube
      rm -rf /etc/kubernetes/*
      rm -rf /etc/cni/*
      rm -rf /var/lib/kubelet/*
      rm -rf /var/lib/etcd/*

  - name: Installing required packages
    yum:
     name: "{{ packages }}"
     state: present

  - name: Starting and Enabling the required services
    service:
     name: "{{ item }}"
     state: started
     enabled: yes
    with_items: "{{ services }}"

  - name: Enabling Bridge Firewall Rule
    shell: "echo '1' > /proc/sys/net/bridge/bridge-nf-call-iptables"

  - name: Pulling images required for setting up a Kubernetes cluster
    shell: kubeadm config images pull
